run:
  date_from: "2025-01-01"
  date_to: "2025-01-31"
  timezone: "Europe/London"

metoffice:
  downwind_tolerance_deg: 25

sites:
  - id: newhaven_incinerator
    name: "Newhaven ERF"
    role: target
    lat: 50.796
    lon: 0.055

  - id: lewes
    name: "Lewes"
    role: control
    lat: 50.873
    lon: 0.008

  - id: eastbourne
    name: "Eastbourne"
    role: control
    lat: 50.768
    lon: 0.290

  - id: brighton
    name: "Brighton"
    role: control
    lat: 50.822
    lon: -0.137

  - id: seaford_control
    name: "Seaford (control)"
    role: control
    lat: 50.772
    lon: 0.102
