#!/usr/bin/env python3
"""Validate AQ26 weekly operational outputs before upload/deploy."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import yaml


def load_yaml(path: str | Path) -> dict:
    p = Path(path)
    if not p.exists():
        return {}
    return yaml.safe_load(p.read_text(encoding="utf-8")) or {}


def fail(message: str) -> None:
    raise SystemExit(f"VALIDATION FAILED: {message}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", default="configs/aq26_weekly_runtime.yml")
    args = parser.parse_args()

    runtime = load_yaml(args.config)
    paths = runtime.get("paths", {})
    public = Path(paths.get("public_site", "site_public"))
    unredacted = Path(paths.get("unredacted_site", "site_unredacted"))
    downloads_public = Path(paths.get("downloads_public", "site_public/downloads"))
    weekly = Path(paths.get("weekly_data", "site_public/data/weekly"))

    if not public.exists():
        fail(f"Missing public site folder: {public}")
    if not unredacted.exists():
        fail(f"Missing unredacted site folder: {unredacted}")

    for page in runtime.get("required_public_pages", []):
        p = public / page
        if not p.exists() or p.stat().st_size < 50:
            fail(f"Missing or blank public page: {p}")

    for page in runtime.get("required_unredacted_pages", []):
        p = unredacted / page
        if not p.exists() or p.stat().st_size < 50:
            fail(f"Missing or blank unredacted page: {p}")

    bundle = downloads_public / "AQ26_WEEKLY_EVIDENCE_BUNDLE.zip"
    if not bundle.exists() or bundle.stat().st_size < 100:
        fail(f"Missing or tiny evidence bundle: {bundle}")

    status_json = weekly / "backfill-status.json"
    if not status_json.exists():
        fail(f"Missing backfill status JSON: {status_json}")
    try:
        json.loads(status_json.read_text(encoding="utf-8"))
    except Exception as exc:
        fail(f"Invalid JSON in {status_json}: {exc}")

    for root in [public, unredacted]:
        for bad in root.rglob(".htpasswd"):
            fail(f".htpasswd must not be committed/generated by workflow: {bad}")

    print("AQ26 validation passed.")


if __name__ == "__main__":
    main()
