#!/usr/bin/env python3
"""
AQ26 legacy unredacted-site builder compatibility wrapper.

This file replaces an older script that had invalid f-string syntax.  The
current preferred builders are:
  - scripts/aq26_build_operational_dual_site.py
  - scripts/aq26_build_weekly_alert_pages.py

This wrapper remains intentionally small so any old workflow that still calls
aq26_build_unredacted_site.py will not fail the repository syntax audit.
"""
from __future__ import annotations

import argparse
import html
import json
from datetime import datetime, timezone
from pathlib import Path


def esc(value: object) -> str:
    return html.escape("" if value is None else str(value), quote=True)


def now_utc() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo-root", default=".")
    ap.add_argument("--public-site", default="site_public")
    ap.add_argument("--output-site", default="site_unredacted")
    ap.add_argument("--max-index-files", default="250")
    args = ap.parse_args()

    repo = Path(args.repo_root).resolve()
    public = repo / args.public_site
    out = repo / args.output_site
    assets = out / "assets"
    data_dir = out / "data" / "legacy"
    assets.mkdir(parents=True, exist_ok=True)
    data_dir.mkdir(parents=True, exist_ok=True)

    for name in ["air_quality_web.svg", "favicon.svg", "logo_web.svg"]:
        for src in [repo / "website" / "assets" / name, public / "assets" / name]:
            if src.exists():
                (assets / name).write_bytes(src.read_bytes())
                break

    summary = {
        "generated_utc": now_utc(),
        "status": "legacy_wrapper",
        "note": "Use aq26_build_operational_dual_site.py for the full unredacted site.",
        "public_site": str(public),
        "output_site": str(out),
    }
    (data_dir / "legacy_unredacted_wrapper_summary.json").write_text(
        json.dumps(summary, indent=2), encoding="utf-8"
    )

    body = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="robots" content="noindex,nofollow">
  <title>AQ26 Unredacted Review</title>
  <link rel="icon" href="assets/favicon.svg" type="image/svg+xml">
  <style>
    body{{font-family:system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif;margin:0;background:#eef5fb;color:#071a30}}
    header{{background:#071a30;color:#fff;padding:1rem 1.25rem}}
    main{{max-width:1100px;margin:auto;padding:2rem 1rem}}
    .card{{background:#fff;border:1px solid #d9e4ef;border-radius:22px;padding:1.2rem;margin:1rem 0;box-shadow:0 16px 36px rgba(7,26,48,.12)}}
    img.logo{{max-height:72px;width:auto;background:#fff;border-radius:12px;padding:.35rem}}
    a{{color:#0b4d83;font-weight:800}}
  </style>
</head>
<body>
<header><img class="logo" src="assets/air_quality_web.svg" alt="SCC Nexus Air Quality Report"> <b>AQ26 unredacted review</b></header>
<main>
  <section class="card">
    <h1>Unredacted review site compatibility page</h1>
    <p>This page was generated by the legacy compatibility wrapper at {esc(now_utc())}.</p>
    <p>The full protected review site is generated by <code>aq26_build_operational_dual_site.py</code>.</p>
    <p><a href="evidence.html">Open evidence page</a> · <a href="candidates.html">Open candidates page</a> · <a href="../index.html">Public site</a></p>
  </section>
</main>
</body>
</html>
"""
    (out / "index.html").write_text(body, encoding="utf-8")
    (out / "robots.txt").write_text("User-agent: *\nDisallow: /\n", encoding="utf-8")
    print(json.dumps(summary, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
