#!/usr/bin/env python3
"""Remove generated side-label text beside the AQ26 header logo.

Safe post-build polish for site_public, site_unredacted and site_test trees.
It removes repeated branding text such as "SCC Nexus · AQ26" while preserving
logo images, nav/menu, weekly alerts and moving banners.
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Dict, List

LABEL_PATTERNS = [
    r"\s*<span[^>]*>\s*<small[^>]*>\s*SCC\s+Nexus\s*[·&middot;|\-–—]*\s*AQ26\s*</small>\s*</span>\s*",
    r"\s*<span[^>]*>\s*SCC\s+Nexus\s*[·&middot;|\-–—]*\s*AQ26\s*</span>\s*",
    r"\s*<small[^>]*>\s*SCC\s+Nexus\s*[·&middot;|\-–—]*\s*AQ26\s*</small>\s*",
    r"SCC\s+NEXUS\s*[·&middot;|\-–—]*\s*AQ26",
    r"SCC\s+Nexus\s*[·&middot;|\-–—]*\s*AQ26",
]

# Remove the now-empty brand text wrapper if generated by earlier templates.
EMPTY_SPAN_PATTERNS = [
    r"\s*<span[^>]*>\s*</span>\s*",
    r"\s*<div[^>]*class=[\"'][^\"']*(?:brand-text|brand-copy|brand-label)[^\"']*[\"'][^>]*>\s*</div>\s*",
]


def fix_text(txt: str) -> str:
    out = txt
    for pat in LABEL_PATTERNS:
        out = re.sub(pat, "", out, flags=re.I | re.S)
    for pat in EMPTY_SPAN_PATTERNS:
        out = re.sub(pat, "", out, flags=re.I | re.S)
    # Repair excess whitespace between brand link/image and nav/menu only in a harmless way.
    out = re.sub(r"(</a>)\s{2,}(<nav\b)", r"\1\n\2", out, flags=re.I)
    return out


def scan_bad(root: Path) -> List[str]:
    bad: List[str] = []
    if not root.exists():
        return bad
    rx = re.compile(r"SCC\s+Nexus\s*[·&middot;|\-–—]*\s*AQ26|SCC\s+NEXUS\s*[·&middot;|\-–—]*\s*AQ26", re.I)
    for p in sorted(root.rglob("*.html")):
        try:
            if rx.search(p.read_text(encoding="utf-8", errors="replace")):
                bad.append(str(p))
        except Exception:
            continue
    return bad


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--roots", nargs="+", default=["site_test", "site_public", "site_unredacted"])
    ap.add_argument("--summary", default="site_test/data/header_text_polish_summary.json")
    ap.add_argument("--fail-if-found", action="store_true")
    args = ap.parse_args()

    changed: List[str] = []
    checked = 0
    for root_name in args.roots:
        root = Path(root_name)
        if not root.exists():
            continue
        for p in sorted(root.rglob("*.html")):
            checked += 1
            txt = p.read_text(encoding="utf-8", errors="replace")
            fixed = fix_text(txt)
            if fixed != txt:
                p.write_text(fixed, encoding="utf-8")
                changed.append(str(p))

    bad: List[str] = []
    for root_name in args.roots:
        bad.extend(scan_bad(Path(root_name)))

    summary = {"ok": not bad, "checked_html_files": checked, "changed_files": changed, "remaining_matches": bad}
    out = Path(args.summary)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print(json.dumps(summary, indent=2))

    if args.fail_if_found and bad:
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
